### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by soroush-bn** [soroush-bn/AI-search-project#1]
- [x]  adding all models 
- [x] adding input to models mapper
- [x] adding model to node mapper
- [x] implementing movement functions
- [x] implementing AI for movements

**Comment by soroush-bn** [comment]
- [x] draw map on each movement state
- [ ] refactor and clean code
